name: Deploy to ScratchOrg3 (release)

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli@latest

      - name: Authenticate to Org3
        env:
          SF_CLIENT_ID: ${{ secrets.SF_CLIENT_ID_ORG3 }}
          SF_JWT_KEY: ${{ secrets.SF_JWT_KEY_ORG3 }}
          SF_USERNAME: ${{ secrets.SF_USERNAME_ORG3 }}
          SF_ORG_INSTANCE_URL: ${{ secrets.SF_INSTANCE_URL_ORG3 }}
        run: |
          echo "$SF_JWT_KEY" > jwt.key
          sf org login jwt --client-id $SF_CLIENT_ID --jwt-key-file jwt.key --username $SF_USERNAME --instance-url $SF_ORG_INSTANCE_URL
          sf org display --target-org $SF_USERNAME

      - name: Deploy to Org3
        run: sf project deploy start --target-org ${{ secrets.SF_USERNAME_ORG3 }} --source-dir force-app/main/default --wait 10
