name: Deploy to Production (main)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SFDX
        uses: sfdx-actions/setup-sfdx@v3

      - name: Authenticate to Final Org
        env:
          SFDX_CLIENT_ID: ${{ secrets.SF_CLIENT_ID_PROD }}
          SFDX_JWT_KEY: ${{ secrets.SF_JWT_KEY_PROD }}
          SFDX_USERNAME: ${{ secrets.SF_USERNAME_PROD }}
          SFDX_INSTANCE_URL: ${{ secrets.SF_INSTANCE_URL_PROD }}
        run: |
          echo "$SFDX_JWT_KEY" > assets/server.key
          sfdx auth:jwt:grant --clientid $SFDX_CLIENT_ID --jwtkeyfile assets/server.key --username $SFDX_USERNAME --instanceurl $SFDX_INSTANCE_URL

      - name: Deploy to Production
        run: sfdx force:source:deploy -u ${{ secrets.SF_USERNAME_PROD }} -p force-app/main/default -w 10
