name: Deploy to Production (main)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli@latest

      - name: Authenticate to Final Org
        env:
          SF_CLIENT_ID: ${{ secrets.SF_CLIENT_ID_PROD }}
          SF_JWT_KEY: ${{ secrets.SF_JWT_KEY_PROD }}
          SF_USERNAME: ${{ secrets.SF_USERNAME_PROD }}
          SF_ORG_INSTANCE_URL: ${{ secrets.SF_INSTANCE_URL_PROD }}
        run: |
          echo "$SF_JWT_KEY" > jwt.key
          sf org login jwt --client-id "$SF_CLIENT_ID" --jwt-key-file jwt.key --username "$SF_USERNAME" --instance-url "$SF_ORG_INSTANCE_URL"
          sf org display --target-org "$SF_USERNAME"

      - name: Deploy to Production
        run: sf project deploy start --target-org ${{ secrets.SF_USERNAME_PROD }} --source-dir force-app/main/default --wait 10
